name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  
  # Deployment of the frontend
  deploy_frontend:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Cache Eleventy .cache
        uses: actions/cache@v3
        with:
            path: ./.cache
            key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm install
      
      - run: npm run build

      - name: Deploy to S3
        run: aws s3 sync ./_site s3://foxdog.blog --delete

      - name: Create CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} --paths "/*"
  